jettyUrl = 'http://localhost:8081/'

def servers

stage 'Chef'
node {
    sh "mkdir .chef"
    dir('.chef') {
      writeFile encoding: 'UTF-8', file: 'knife.rb', text: '''current_dir = File.dirname(__FILE__)
log_level                :info
log_location             STDOUT
node_name                "alexmanly"
client_key               "#{current_dir}/user.pem"
validation_client_name   "tesco-poc-validator"
validation_key           "#{current_dir}/tesco-poc-validator.pem"
chef_server_url          "https://52.50.93.12/organizations/tesco-poc"
cookbook_path            ["#{current_dir}/../cookbooks"]'''
      writeFile encoding: 'UTF-8', file: 'user.pem', text: '''<INSERT_KEY_HERE>'''
    }
    sh 'knife ssl fetch'
    sh 'knife node list'
}

stage 'Dev'
node {
    checkout scm
    servers = load 'servers.groovy'
    mvn '-o clean package'
    dir('target') {stash name: 'war', includes: 'x.war'}
}

stage 'QA'
parallel(longerTests: {
    runTests(servers, 30)
}, quickerTests: {
    runTests(servers, 20)
})

stage name: 'Staging', concurrency: 1
node {
    servers.deploy 'staging'
}

input message: "Does ${jettyUrl}staging/ look good?"
try {
    checkpoint('Before production')
} catch (NoSuchMethodError _) {
    echo 'Checkpoint feature available in CloudBees Jenkins Enterprise.'
}

stage name: 'Production', concurrency: 1
node {
    sh "wget -O - -S ${jettyUrl}staging/"
    echo 'Production server looks to be alive'
    servers.deploy 'production'
    echo "Deployed to ${jettyUrl}production/"
}

def mvn(args) {
    sh "${tool 'Maven 3.x'}/bin/mvn ${args}"
}

def runTests(servers, duration) {
    node {
        checkout scm
        servers.runWithServer {id ->
            mvn "-o -f sometests test -Durl=${jettyUrl}${id}/ -Dduration=${duration}"
        }
    }
}
